version: "3.5"

services:
  mosquitto:
    build: .
    image: eclipse-mosquitto
    container_name: mosquitto
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    restart: always
    volumes:
      - ./config:/mosquitto/config:ro
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtt

networks:
  mqtt:
    driver: bridge
    name: mqtt-elk

volumes:
  mosquitto-data:
  mosquitto-log:
